* Changelog
** v0.0.5
*** Features
**** Backlinks
:PROPERTIES:
:ID:       a08e2a03-19be-46b0-96fc-43a6556e3710
:END:
 - Add a function ~org-z-backlinks-at-point~ that can be used to inspect backlinks to the current headline. This function uses completing-read to allow jumping through a backlink. This function is not bound to any key by default, leaving keybindings open to the user.

 - If org-eldoc is loaded, show the number of backlinks for the current headline at point. This functionality can be turned off by unsetting ~org-z-show-backlinks~.

   This function respects ~eldoc-echo-area-use-multiline-p~. If t, then the backlink message is always displayed on a new line. If truthy, message is displayed same line if there's space, or a new line if there is not enough space. If false, it is always displayed on single line (header path will be truncated).
** v0.0.4
*** Bug fixes
**** Fix org-z-selectrum
~selectrum-read~ was deprecated and removed from selectrum. Use ~selectrum--read~ instead.
** v0.0.3
*** Bug fixes
**** Fix completion backends
***** Fix missing imports
These were causing errors like: ~Symbol's function definition is void: org-ql-search-directories-files~.
***** Fix helm backend not showing results
Because ~org-z--format-org-ql-heading~ returned a cons cell, ~org-ql-select~ tried to flatten it and failed silently due to ~ignore-errors~. Return text with a point-marker property instead.
** v0.0.2
*** Breaking changes
**** Completion backends
org-z now supports both Helm and Selectrum for completion. The completion backend must be explicitly set by loading one of ~org-z-helm~ or ~org-z-selectrum~ (which each depend on a respective completion framework) in addition to ~org-z~. Working configuration looks like this:

#+begin_src emacs-lisp
  (use-package org-z
    :straight (org-z :type git :host github :repo "landakram/org-z")
    :config
    (org-z-mode 1))

  (use-package org-z-selectrum
    :straight (org-z-selectrum :type git :host github :repo "landakram/org-z"))
#+end_src
*** Features
**** Sort links with prescient.el
Results can be optionally sorted with [[https://github.com/raxod502/prescient.el][prescient.el]] by setting ~org-z-use-prescient~. Note that if you already have prescient enabled through your completion system, you should leave this as nil. 
